using Npgsql;
using NpgsqlTypes;
using rabota.Models;
namespace rabota.Services;
public class DatabaseService
{
    private readonly string cs; public DatabaseService(string connectionString) => cs = connectionString;
    static void T(NpgsqlCommand c, string n, string v) => c.Parameters.Add(new NpgsqlParameter(n, NpgsqlDbType.Text) { Value = v ?? "" });
    static void NT(NpgsqlCommand c, string n, string? v) => c.Parameters.Add(new NpgsqlParameter(n, NpgsqlDbType.Text) { Value = string.IsNullOrWhiteSpace(v) ? DBNull.Value : v });
    static void I(NpgsqlCommand c, string n, int v) => c.Parameters.Add(new NpgsqlParameter(n, NpgsqlDbType.Integer) { Value = v });
    static void NI(NpgsqlCommand c, string n, int? v) => c.Parameters.Add(new NpgsqlParameter(n, NpgsqlDbType.Integer) { Value = v.HasValue ? v.Value : DBNull.Value });
    static void N(NpgsqlCommand c, string n, decimal v) => c.Parameters.Add(new NpgsqlParameter(n, NpgsqlDbType.Numeric) { Value = v });
    static void D(NpgsqlCommand c, string n, DateTime? v) => c.Parameters.Add(new NpgsqlParameter(n, NpgsqlDbType.Date) { Value = v.HasValue ? v.Value.Date : DBNull.Value });
    static string S(NpgsqlDataReader r, int i) => r.IsDBNull(i) ? "" : r.GetString(i);
    public async Task<User?> AuthenticateAsync(string u, string p) { await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); await using var q = new NpgsqlCommand("SELECT user_id,username,password_hash,role,full_name FROM users WHERE username=@u AND password_hash=@p", c); T(q, "@u", u); T(q, "@p", p); await using var r = await q.ExecuteReaderAsync(); if (!await r.ReadAsync()) return null; return new User { UserId = r.GetInt32(0), Username = r.GetString(1), PasswordHash = r.GetString(2), Role = r.GetString(3), FullName = r.GetString(4) }; }
    public async Task<bool> RegisterUserAsync(string u, string p, string role, string full) { await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); await using var q = new NpgsqlCommand("INSERT INTO users(username,password_hash,role,full_name) VALUES(@u,@p,@r,@f)", c); T(q, "@u", u); T(q, "@p", p); T(q, "@r", role); T(q, "@f", full); await q.ExecuteNonQueryAsync(); return true; }
    public async Task<List<Client>> GetClientsAsync(string search = "") { var a = new List<Client>(); await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); await using var q = new NpgsqlCommand("SELECT client_id,full_name,phone,email,passport_data,address,birth_date,created_at FROM clients WHERE @s='' OR full_name ILIKE '%'||@s||'%' OR phone ILIKE '%'||@s||'%' OR email ILIKE '%'||@s||'%' ORDER BY full_name", c); T(q, "@s", search); await using var r = await q.ExecuteReaderAsync(); while (await r.ReadAsync()) a.Add(new Client { ClientId = r.GetInt32(0), FullName = r.GetString(1), Phone = S(r, 2), Email = S(r, 3), PassportData = S(r, 4), Address = S(r, 5), BirthDate = r.IsDBNull(6) ? null : r.GetDateTime(6), CreatedAt = r.GetDateTime(7) }); return a; }
    public async Task AddClientAsync(Client x) { await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); await using var q = new NpgsqlCommand("INSERT INTO clients(full_name,phone,email,passport_data,address,birth_date) VALUES(@f,@p,@e,@pa,@a,@d)", c); T(q, "@f", x.FullName); NT(q, "@p", x.Phone); NT(q, "@e", x.Email); NT(q, "@pa", x.PassportData); NT(q, "@a", x.Address); D(q, "@d", x.BirthDate); await q.ExecuteNonQueryAsync(); }
    public async Task<List<Account>> GetAccountsAsync(int? clientId = null, string? accountType = null, string? searchAccountNumber = null, bool sortByBalance = false) { var a = new List<Account>(); await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); string o = sortByBalance ? "a.balance DESC" : "a.account_id"; string sql = $"SELECT a.account_id,a.client_id,a.account_number,a.account_type,a.balance,a.status,a.opened_at,c.full_name FROM accounts a JOIN clients c ON c.client_id=a.client_id WHERE (@cid IS NULL OR a.client_id=@cid) AND (@type IS NULL OR a.account_type=@type) AND (@s='' OR a.account_number ILIKE '%'||@s||'%') ORDER BY {o}"; await using var q = new NpgsqlCommand(sql, c); NI(q, "@cid", clientId); NT(q, "@type", accountType); T(q, "@s", searchAccountNumber ?? ""); await using var r = await q.ExecuteReaderAsync(); while (await r.ReadAsync()) a.Add(new Account { AccountId = r.GetInt32(0), ClientId = r.GetInt32(1), AccountNumber = r.GetString(2), AccountType = r.GetString(3), Balance = r.GetDecimal(4), Status = r.GetString(5), OpenedAt = r.GetDateTime(6), ClientName = r.GetString(7) }); return a; }
    public async Task<List<string>> GetAccountTypesAsync() { var a = new List<string>(); await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); await using var q = new NpgsqlCommand("SELECT DISTINCT account_type FROM accounts ORDER BY account_type", c); await using var r = await q.ExecuteReaderAsync(); while (await r.ReadAsync()) a.Add(r.GetString(0)); return a; }
    public async Task<List<TransactionItem>> GetTransactionsAsync(int? accountId = null) { var a = new List<TransactionItem>(); await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); await using var q = new NpgsqlCommand("SELECT t.transaction_id,t.account_id,a.account_number,t.transaction_type,t.amount,t.description,t.created_at FROM transactions t JOIN accounts a ON a.account_id=t.account_id WHERE @id IS NULL OR t.account_id=@id ORDER BY t.created_at DESC", c); NI(q, "@id", accountId); await using var r = await q.ExecuteReaderAsync(); while (await r.ReadAsync()) a.Add(new TransactionItem { TransactionId = r.GetInt32(0), AccountId = r.GetInt32(1), AccountNumber = r.GetString(2), TransactionType = r.GetString(3), Amount = r.GetDecimal(4), Description = S(r, 5), CreatedAt = r.GetDateTime(6) }); return a; }
    public async Task CreateTransactionAsync(string sender, string receiver, decimal amount, string description) { if (amount <= 0) throw new Exception("Сумма должна быть больше нуля."); await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); await using var tx = await c.BeginTransactionAsync(); try { const string f = "SELECT account_id,balance,status FROM accounts WHERE account_number=@n FOR UPDATE"; int sid, rid; decimal bal; await using (var q = new NpgsqlCommand(f, c, tx)) { T(q, "@n", sender); await using var r = await q.ExecuteReaderAsync(); if (!await r.ReadAsync()) throw new Exception("Счет отправителя не найден."); sid = r.GetInt32(0); bal = r.GetDecimal(1); if (r.GetString(2) != "Активен") throw new Exception("Счет отправителя неактивен."); } await using (var q = new NpgsqlCommand(f, c, tx)) { T(q, "@n", receiver); await using var r = await q.ExecuteReaderAsync(); if (!await r.ReadAsync()) throw new Exception("Счет получателя не найден."); rid = r.GetInt32(0); if (r.GetString(2) != "Активен") throw new Exception("Счет получателя неактивен."); } if (sid == rid) throw new Exception("Нельзя переводить деньги на тот же счет."); if (bal < amount) throw new Exception("Недостаточно средств на счете."); await using (var q = new NpgsqlCommand("UPDATE accounts SET balance=balance-@a WHERE account_id=@i", c, tx)) { N(q, "@a", amount); I(q, "@i", sid); await q.ExecuteNonQueryAsync(); } await using (var q = new NpgsqlCommand("UPDATE accounts SET balance=balance+@a WHERE account_id=@i", c, tx)) { N(q, "@a", amount); I(q, "@i", rid); await q.ExecuteNonQueryAsync(); } const string ins = "INSERT INTO transactions(account_id,transaction_type,amount,description) VALUES(@i,@t,@a,@d)"; await using (var q = new NpgsqlCommand(ins, c, tx)) { I(q, "@i", sid); T(q, "@t", "Перевод"); N(q, "@a", amount); T(q, "@d", description); await q.ExecuteNonQueryAsync(); } await using (var q = new NpgsqlCommand(ins, c, tx)) { I(q, "@i", rid); T(q, "@t", "Зачисление"); N(q, "@a", amount); T(q, "@d", description); await q.ExecuteNonQueryAsync(); } await tx.CommitAsync(); } catch { await tx.RollbackAsync(); throw; } }
    public async Task<List<Loan>> GetLoansAsync() { var a = new List<Loan>(); await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); await using var q = new NpgsqlCommand("SELECT l.loan_id,l.client_id,l.loan_number,l.amount,l.interest_rate,l.remaining_amount,l.status,l.start_date,l.end_date,c.full_name FROM loans l JOIN clients c ON c.client_id=l.client_id ORDER BY l.start_date DESC", c); await using var r = await q.ExecuteReaderAsync(); while (await r.ReadAsync()) a.Add(new Loan { LoanId = r.GetInt32(0), ClientId = r.GetInt32(1), LoanNumber = r.GetString(2), Amount = r.GetDecimal(3), InterestRate = r.GetDecimal(4), RemainingAmount = r.GetDecimal(5), Status = r.GetString(6), StartDate = r.GetDateTime(7), EndDate = r.IsDBNull(8) ? null : r.GetDateTime(8), ClientName = r.GetString(9) }); return a; }
    public async Task<List<Deposit>> GetDepositsAsync() { var a = new List<Deposit>(); await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); await using var q = new NpgsqlCommand("SELECT d.deposit_id,d.client_id,d.deposit_number,d.amount,d.interest_rate,d.status,d.start_date,d.end_date,c.full_name FROM deposits d JOIN clients c ON c.client_id=d.client_id ORDER BY d.start_date DESC", c); await using var r = await q.ExecuteReaderAsync(); while (await r.ReadAsync()) a.Add(new Deposit { DepositId = r.GetInt32(0), ClientId = r.GetInt32(1), DepositNumber = r.GetString(2), Amount = r.GetDecimal(3), InterestRate = r.GetDecimal(4), Status = r.GetString(5), StartDate = r.GetDateTime(6), EndDate = r.IsDBNull(7) ? null : r.GetDateTime(7), ClientName = r.GetString(8) }); return a; }
    public async Task<List<Employee>> GetEmployeesAsync() { var a = new List<Employee>(); await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); await using var q = new NpgsqlCommand("SELECT e.employee_id,e.full_name,e.position,e.phone,e.email,e.branch_id,e.hire_date,COALESCE(b.name,'') FROM employees e LEFT JOIN branches b ON b.branch_id=e.branch_id ORDER BY e.full_name", c); await using var r = await q.ExecuteReaderAsync(); while (await r.ReadAsync()) a.Add(new Employee { EmployeeId = r.GetInt32(0), FullName = r.GetString(1), Position = r.GetString(2), Phone = S(r, 3), Email = S(r, 4), BranchId = r.IsDBNull(5) ? null : r.GetInt32(5), HireDate = r.GetDateTime(6), BranchName = r.GetString(7) }); return a; }
    public async Task<List<Branch>> GetBranchesAsync() { var a = new List<Branch>(); await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); await using var q = new NpgsqlCommand("SELECT branch_id,name,address,phone,manager_name FROM branches ORDER BY name", c); await using var r = await q.ExecuteReaderAsync(); while (await r.ReadAsync()) a.Add(new Branch { BranchId = r.GetInt32(0), Name = r.GetString(1), Address = r.GetString(2), Phone = S(r, 3), ManagerName = S(r, 4) }); return a; }
    public async Task<List<Payment>> GetPaymentsAsync(string? accountNumber = null) { var a = new List<Payment>(); await using var c = new NpgsqlConnection(cs); await c.OpenAsync(); await using var q = new NpgsqlCommand("SELECT p.payment_id,p.account_id,p.amount,p.purpose,p.status,p.payment_date,a.account_number FROM payments p JOIN accounts a ON a.account_id=p.account_id WHERE @n IS NULL OR a.account_number=@n ORDER BY p.payment_date DESC", c); NT(q, "@n", accountNumber); await using var r = await q.ExecuteReaderAsync(); while (await r.ReadAsync()) a.Add(new Payment { PaymentId = r.GetInt32(0), AccountId = r.GetInt32(1), Amount = r.GetDecimal(2), Purpose = S(r, 3), Status = r.GetString(4), PaymentDate = r.GetDateTime(5), AccountNumber = r.GetString(6) }); return a; }
}
